### ISSUE TITLE
webui: Times should be clearly indicated with AM/PM and time zone

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#191]
Currently the time is in 24hour format and it doesn't specify time zone.

The time should be in 12hour am/pm format with a clear time zone indicated 

<img width="1366" alt="screen shot 2017-09-30 at 12 13 03 pm" src="https://user-images.githubusercontent.com/17053096/31047452-0d3eafba-a5d9-11e7-9615-8ac0dbf00afd.png">

**Comment by iandees** [comment]
See also #58.

Getting timezones right will be hard with our current system because figuring out the timezone for any particular point on the globe (since we allow people to start/end their carpools anywhere) is a little tricky.

**Comment by iandees** [comment]
The new interface only asks for hour and includes a more obvious AM/PM, but it doesn't account for timezone.

We can do some more work on timezones, but we should make sure we're clear on what the user might expect:

1. The user will probably think of their carpool start and end times in the local timezone, whatever that might be (like airline tickets). If someone creates a carpool with a departure in Chicago (Central) and arrival in Indiana (Eastern), they want see departure time in Central and return time in Eastern.
1. Since we're focusing on Virginia for now, we can probably assume everyone will be in Eastern. Probably.

Google Maps API has a [Timezone API](https://developers.google.com/maps/documentation/timezone/intro) that we could use to help with this.

**Comment by dryan** [comment]
The UI now has AM/PM listed. 

I'm inclined to agree that timezone isn't something we need to track but it should be entered based on the destination. And I imagine that's what almost every driver would do by nature anyway.
