### ISSUE TITLE
/carpools/find - unable to click on a carpool to proceed to next step

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#265]
An authenticated user (rider) that wants to join a carpool is unable to click on the ride information to proceed to next step, which would be to request a ride.

<img width="1546" alt="screen shot 2017-10-08 at 8 14 35 am" src="https://user-images.githubusercontent.com/17053096/31316701-bcdc63b8-ac00-11e7-93b6-b69814738a12.png">

**Comment by iandees** [comment]
@schloo, when clicking this loads content into the `#detail-pane` div:

https://github.com/RagtagOpen/nomad/blob/754904bc76e005c9fa0a7d98a067290beaca2cd1/app/templates/carpools/find.html#L42-L51

 That div doesn't seem to ever get shown though. Can you look into why?

**Comment by iandees** [comment]
In https://github.com/RagtagOpen/nomad/pull/283/commits/78ea8287ba147a4afa0567095152217887dca41a I put in a workaround that sends you to the details page for the carpool. Instead of trying to fit things into a div below the map on the find page, perhaps we could style that page so it looks decent and has room for drivers to manage their carpool.

**Comment by schloo** [comment]
@iandees Roger. This pattern will apply to both the driver and rider side, right?

**Comment by iandees** [comment]
Yea, I think so. Right now the "ride details" page handles the details for both the driver and the rider.

**Comment by schloo** [comment]
@iandees just pushed a styled template for `carpools/show`. It's pretty minimal, needs some CSS tweaks but it'll do for now. See PR: #302

**Comment by iandees** [comment]
This goes to a nicely-styled carpool details page now.

**Comment by engerm** [comment]
Tested and verified
