### ISSUE TITLE
Hidden destination should also hide the carpools associated with the destination on the Find page

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#379]
The "Find a Ride" still displays carpools for destinations that are hidden.

Steps:

* create destination
* create carpool using that destination
* load "Find a Ride" page
  * note the destination is there
* change destination to hidden
* load "Find a Ride" page
  * note the destination is there

Actual Result:

A carpool with a hidden destination is still visible to a user (driver, rider)

Expected Result:

1) A carpool with a hidden destination would not be visible on the "Find a Ride" page
2) Only carpools with visible destinations would be visible on the "Find a Ride" page

**Comment by iandees** [comment]
Hmm, this might be really confusing to a driver or rider. To me, hiding a destination means that you don't see it in the list of destinations when creating or editing a carpool.

We could add a "locked" or "blocked" flag or something to carpools so that admins can keep them from showing up in search results.
