### ISSUE TITLE
Campaign: Let campaign export user information and import into their tool

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#89]
Admin site not needed in v1.0

Have a script that can pull information and get into a format for campaign offices to use. 

This could be a flat file or the ability to send data to the campaigns API. At this time there is no information about what type of tool a campaign's office uses

**Comment by flynnwastaken** [comment]
This could be make or break for campaigns deciding to use the tool. If it's inconvenient for them to handle the data and import into their own system, they will be reluctant to add to their data management burden.
In determining test case campaigns, we'll also have to see what campaign management software they're using. All the Congressional races and Senate races will be using NGP-VAN Nationbuilder.
They'll want to add any volunteer work done by traveling volunteers to their records, because the professional organizer class loves a soupçon of analytics.

**Comment by engerm** [comment]
this should go on the /admin page

**Comment by kielni** [comment]
@flynnwastaken can you describe a convenient output format? CSV, Excel, JSON, etc? What fields (email, dates, etc)?

**Comment by jillh510** [comment]
Adding @bradyk to the issue because this affects the privacy policy

**Comment by iandees** [comment]
Let's go with CSV. It would help to know from @flynnwastaken, @jillh510, or @bradyk what columns to include in an export.

**Comment by engerm** [comment]
@flynnwastaken DMed that they would need a "spreadsheet of drivers and riders with contact info is all they'd need".

From that data we have, that would be:
* Display Name
* email address
* phone number
* preferred contact method

**Comment by engerm** [comment]
Confirmed this is working. 

Column headers:

```

Nomad carpool drivers and riders |   |   |   |  
-- | -- | -- | -- | --
destination | carpool leave time | carpool return time | name | email | phone | preferred contact method


```
